version: '3.8'

services:
  mongo:
    image: mongo
    # restart: always
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: duongtrick1
      MONGO_INITDB_ROOT_PASSWORD: '0989542210'
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes'] # Overwrite the CMD
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  redis_data: