version: '3.8'

services:
  mongo:
    image: mongo
    # restart: always
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: duongtrick1
      MONGO_INITDB_ROOT_PASSWORD: '0989542210'
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data